### PR TITLE
Allow event-type-wise DL2 production

### PR DESCRIPTION
**Pull request by TarekHC**
Hi @GernotMaier,

These are the tiny modifications I added to the converter to allow event-type-wise DL2 tables.

The logging code in the end is completely optional, but was very useful at the time to check the statistics within each of the event types.

Tarek

### CODE REVIEW

**Comment by GernotMaier** [comment]
What is about the check that failed? Otherwise fine.

**Comment by TarekHC** [comment]
Hi Gernot, 

I'm trying to understand what is that check, and I'm just not able to do it... So feel free to merge or not...

**Comment by GernotMaier** [comment]
Me neither, we probably can switch this off.

Gernot

> On 7. Jun 2021, at 15:10, Tarek Hassan ***@***.***> wrote:
> 
> 
> Hi Gernot,
> 
> I'm trying to understand what is that check, and I'm just not able to do it... So feel free to merge or not...
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 



---
Dr Gernot Maier
CTA
Deutsches Elektronen-Synchrotron DESY 
Ein Forschungszentrum der Helmholtz-Gemeinschaft
Platanenallee 6, D-15738 Zeuthen, Germany

Tel.: +49  33 7627 7598
Internet: www.desy.de/cta
Besucheradresse: 1X07

**Comment by GernotMaier** [comment]
Coday is slow…attached the errors - the last one is important?

> On 7. Jun 2021, at 15:10, Tarek Hassan ***@***.***> wrote:
> 
> 
> Hi Gernot,
> 
> I'm trying to understand what is that check, and I'm just not able to do it... So feel free to merge or not...
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 



---
Dr Gernot Maier
CTA
Deutsches Elektronen-Synchrotron DESY 
Ein Forschungszentrum der Helmholtz-Gemeinschaft
Platanenallee 6, D-15738 Zeuthen, Germany

Tel.: +49  33 7627 7598
Internet: www.desy.de/cta
Besucheradresse: 1X07

**Pull request merged**
