### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by TarekHC**
Hi @GernotMaier 

I added some info of the content of the generated DL2 files to the README.md.

What I did not do, but maybe we should, is add a sentence like "This format has not been discussed nor approved by the collaboration, and just represents a pragmatic way of sharing intermediate analysis products between eventDisplay and ctapipe.". But I leave that to you!

### CODE REVIEW

**Comment by GernotMaier** [comment]
All good - thanks! I don't think we need this additional comments, as we don't claim anywhere that this is a standard format.

**Comment by TarekHC** [comment]
You rejected the pull request... You don't want the information on the format you are generating? It will be useful for Michele, Max, or anyone that uses these files.

**Comment by GernotMaier** [comment]
I didn't reject it, must be a bug in github!!!
(maybe I pressed the wrong button, but I didn't reject it...)

**Comment by TarekHC** [comment]
Of course not! That would mean you made a mistake, and that is simply impossible.

**Pull request merged**
