### PR TITLE
Sq10 integration

### PR DESCRIPTION
**Pull request by GernotMaier**
Significance changes are introduced with this pull request. Main motivation is to improve the efficiency of the DL2 tree writing and allow to write those tree out by default without using an extensive amount of storage. 

Most significant change:
- new tree *DL2EventTree* replaces *fEventTreeCuts*
-  *DL2EventTree* contains all parameters required for DL2 (no need to have the full/heavy/large *data* tree in the file)
- *EVENT_ID* is filled with bogus numbers (simple increasing numbers), as this is not propagated from the ROOT IRFs

Minor changes:
- removed sites from the command line (issue #1) and hardwired list of sites plus altitude (read from the IRF file now)
- removed hardwired list of telescope types (read from the IRF file now)
- changed to uproot4 (simply because I had a basic python problem which I couldn't solve with uproot; I really have no clue)

This is a draft pull request as I still have to provide / upload examples files for testing.

### CODE REVIEW

**Comment by TarekHC** [comment]
OBS_ID seems to be also needed by pyirf. I can try to fix it if you want.

**Comment by TarekHC** [comment]
Hi @GernotMaier 

I did a quick review of the pull request. The only issue I could find is that we switch to the new eventDisplay format, so previous files (those containing a `fEventTreeCuts` tree) will stop working.

If this is not a problem, green light from my side.

Tarek

**Comment by GernotMaier** [comment]
Hi @TarekHC - that is not an issue for me as I have updated anyway most of the result files.

But let's be careful, I release the current master so that it is easy to go back. OK?

**Comment by GernotMaier** [comment]
To be used for the old-style eventdisplay files:
https://github.com/Eventdisplay/Converters/releases/tag/prod5-v01

**Pull request merged**
